# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "rewired"
mod.name = "Rewired"
mod.group = "dev.coder2195.rewired"
mod.description = "new mod lol"
mod.version = "0.1.0"

publish.modrinth = "DpUuJr9O"
publish.curseforge = "1606379"

mod.mc_releases = ["26.2"]

[fabric]
mod.mc_compat = "~26.2"
deps.fabric_api = "0.152.2+26.2"
deps.fabric_loader = "0.19.3"
deps.fabric_kotlin = "1.13.13+kotlin.2.4.10"


[neoforge]
mod.mc_compat = "[26.2, 26.3)"
deps.neo_loader = "26.2.0.10-beta"
